using Backpacking.Player;
using Backpacking.UI;
using Backpacking.World;
using UnityEngine;

namespace Backpacking.Survival
{
    [System.Serializable]
    public class VitalsState
    {
        public float satiety, hydration, warmth, energy, sickHours, wetness;
    }

    /// <summary>
    /// Food, water, warmth and energy, each 0–100. They change with game time (so they keep pace when
    /// time is sped up), drain faster with exertion, and slow the player down when low.
    /// </summary>
    public class Vitals : MonoBehaviour
    {
        public const float Max = 100f;

        [SerializeField] TimeOfDay timeOfDay;
        [SerializeField] AmbientTemperature temperature;
        [SerializeField] FirstPersonController player;
        [SerializeField] Backpack backpack;
        [SerializeField] WeatherSystem weather;

        [Header("Starting Values")]
        [SerializeField, Range(0f, Max)] float satiety = 80f;
        [SerializeField, Range(0f, Max)] float hydration = 80f;
        [SerializeField, Range(0f, Max)] float warmth = Max;
        [SerializeField, Range(0f, Max)] float energy = 90f;

        [Header("Drain per Game Hour (at rest)")]
        [SerializeField] float satietyDrain = 2.5f;
        [SerializeField] float hydrationDrain = 3.5f;
        [SerializeField] float energyDrain = 3.5f;
        [Tooltip("Energy restored per hour of sleep.")]
        [SerializeField] float sleepRecovery = 13f;

        [Header("Exertion")]
        [SerializeField] float walkingDrainMultiplier = 1.8f;
        [SerializeField] float sprintingDrainMultiplier = 3.5f;
        [Tooltip("Speed (m/s) above which you count as walking rather than resting.")]
        [SerializeField] float walkingSpeedThreshold = 0.5f;

        [Header("Warmth")]
        [Tooltip("Air temperature (°C) that feels neutral at rest with no clothing.")]
        [SerializeField] float neutralTemperature = 20f;
        [Tooltip("°C of body heat generated by walking / sprinting.")]
        [SerializeField] float walkingHeat = 5f;
        [SerializeField] float sprintingHeat = 10f;
        [Tooltip("Warmth lost per hour for each °C below comfort.")]
        [SerializeField] float coolingRate = 1.5f;
        [Tooltip("Warmth regained per hour for each °C above comfort.")]
        [SerializeField] float warmingRate = 3f;

        [Header("Rain & Wind")]
        [Tooltip("Wetness gained per hour in a full downpour without a rain shell.")]
        [SerializeField] float soakingRate = 35f;
        [Tooltip("Fraction of rain that still gets through a rain shell.")]
        [SerializeField, Range(0f, 1f)] float shellLeakage = 0.12f;
        [Tooltip("Wetness lost per hour when out of the rain, before any fire.")]
        [SerializeField] float dryingRate = 12f;
        [Tooltip("Extra drying per hour for each °C of warmth from a nearby fire.")]
        [SerializeField] float fireDryingPerDegree = 2.5f;
        [Tooltip("Fraction of clothing warmth lost when soaked through.")]
        [SerializeField, Range(0f, 1f)] float soakedInsulationLoss = 0.6f;
        [Tooltip("°C of chill from being soaked through, on top of the lost insulation.")]
        [SerializeField] float soakedChill = 3f;
        [Tooltip("°C of wind chill per km/h of wind.")]
        [SerializeField] float windChillPerKmh = 0.12f;

        [Header("Effects")]
        [SerializeField] float tiredThreshold = 30f;
        [SerializeField] float criticalThreshold = 12f;

        float sickHours;
        float wetness;
        bool warnedCold, warnedHungry, warnedThirsty, warnedTired, warnedWet;

        /// <summary>How wet the player's clothes are, 0 dry to 100 soaked.</summary>
        public float Wetness => wetness;
        /// <summary>Current wind chill in °C (0 when sheltered).</summary>
        public float WindChill { get; private set; }

        public float Satiety => satiety;
        public float Hydration => hydration;
        public float Warmth => warmth;
        public float Energy => energy;
        public bool IsSick => sickHours > 0f;

        /// <summary>Set while sleeping; sleeping uses the sleeping bag instead of clothing.</summary>
        public bool IsSleeping { get; set; }
        /// <summary>Set while sleeping inside a tent.</summary>
        public bool IsSheltered { get; set; }

        /// <summary>Air temperature the player feels, including fires and shelter (°C).</summary>
        public float FeltTemperature { get; private set; }
        /// <summary>The temperature (°C) below which the player starts losing warmth.</summary>
        public float ComfortTemperature { get; private set; }

        public void Eat(float amount) => satiety = Mathf.Min(Max, satiety + amount);
        public void Drink(float amount) => hydration = Mathf.Min(Max, hydration + amount);
        public void MakeSick(float hours) => sickHours = Mathf.Max(sickHours, hours);

        public VitalsState CaptureState() => new()
        {
            satiety = satiety,
            hydration = hydration,
            warmth = warmth,
            energy = energy,
            sickHours = sickHours,
            wetness = wetness,
        };

        public void RestoreState(VitalsState state)
        {
            satiety = state.satiety;
            hydration = state.hydration;
            warmth = state.warmth;
            energy = state.energy;
            sickHours = state.sickHours;
            wetness = state.wetness;
        }

        void Update()
        {
            float hours = Time.deltaTime * timeOfDay.HoursPerSecond;
            if (hours <= 0f)
                return;

            bool moving = !IsSleeping && player.HorizontalSpeed > walkingSpeedThreshold;
            bool sprinting = moving && player.IsSprinting;
            float exertion = sprinting ? sprintingDrainMultiplier : moving ? walkingDrainMultiplier : 1f;
            // A heavy pack makes every step cost more.
            if (moving)
                exertion *= backpack.LoadExertionMultiplier;
            float sickness = IsSick ? 2f : 1f;

            satiety = Mathf.Max(0f, satiety - satietyDrain * exertion * Mathf.Sqrt(sickness) * hours);
            hydration = Mathf.Max(0f, hydration - hydrationDrain * exertion * sickness * hours);
            sickHours = Mathf.Max(0f, sickHours - hours);

            UpdateWarmth(hours, sprinting ? sprintingHeat : moving ? walkingHeat : 0f);

            if (IsSleeping)
                energy = Mathf.Min(Max, energy + sleepRecovery * hours);
            else
            {
                // Being frozen or starving wears you out much faster.
                float strain = warmth <= 0f || satiety <= 0f || hydration <= 0f ? 3f : 1f;
                energy = Mathf.Max(0f, energy - energyDrain * exertion * strain * hours);
            }

            ApplyEffects();
            WarnOnce(ref warnedCold, warmth, 40f, "You're getting cold. Put on a layer or find warmth.");
            WarnOnce(ref warnedHungry, satiety, 25f, "You're hungry.");
            WarnOnce(ref warnedThirsty, hydration, 25f, "You're thirsty.");
            WarnOnce(ref warnedTired, energy, 20f, "You're exhausted. You need sleep.");
        }

        void UpdateWetness(float hours, float fireWarmth)
        {
            bool inTent = IsSleeping && IsSheltered;
            float rain = weather != null && !inTent ? weather.RainIntensity : 0f;
            float soaking = rain * soakingRate * (backpack.WearingWaterproof ? shellLeakage : 1f);
            float drying = (rain > 0.05f ? 0f : dryingRate) + fireWarmth * fireDryingPerDegree;
            wetness = Mathf.Clamp(wetness + (soaking - drying) * hours, 0f, Max);
            WarnOnce(ref warnedWet, Max - wetness, Max - 50f, "You're getting soaked. Put on your rain shell or find shelter.");
        }

        void UpdateWarmth(float hours, float bodyHeat)
        {
            float air = temperature.GetTemperature(transform.position);
            float fire = HeatSource.WarmthAt(transform.position);
            UpdateWetness(hours, fire);

            bool inTent = IsSleeping && IsSheltered;
            WindChill = weather != null && !inTent ? weather.WindKmh * windChillPerKmh : 0f;
            float soaked = wetness / Max;
            FeltTemperature = air + fire + (inTent ? backpack.TentShelter : 0f) - WindChill - soaked * soakedChill;

            float insulation = backpack.ClothingInsulation * (1f - soakedInsulationLoss * soaked);
            ComfortTemperature = IsSleeping
                ? backpack.SleepingBagComfort
                : neutralTemperature - insulation - bodyHeat;

            float difference = FeltTemperature - ComfortTemperature;
            float rate = difference < 0f ? coolingRate : warmingRate;
            warmth = Mathf.Clamp(warmth + difference * rate * hours, 0f, Max);
        }

        void ApplyEffects()
        {
            float lowest = Mathf.Min(Mathf.Min(satiety, hydration), Mathf.Min(warmth, energy));
            float condition = lowest < criticalThreshold ? 0.6f : lowest < tiredThreshold ? 0.85f : 1f;
            player.SpeedMultiplier = condition * backpack.LoadSpeedMultiplier;
            player.CanSprint = energy > criticalThreshold && hydration > criticalThreshold && !backpack.IsOverloaded;
        }

        /// <summary>Posts a message when a value drops below a threshold, then rearms once it recovers.</summary>
        static void WarnOnce(ref bool warned, float value, float threshold, string message)
        {
            if (!warned && value < threshold)
            {
                warned = true;
                Notifications.Post(message);
            }
            else if (warned && value > threshold + 10f)
                warned = false;
        }
    }
}
