using Backpacking.Player;
using Backpacking.UI;
using Backpacking.World;
using UnityEngine;

namespace Backpacking.Survival
{
    [System.Serializable]
    public class VitalsState
    {
        public float satiety, hydration, warmth, energy, sickHours, wetness;
        public float health = Vitals.Max;
        // Saves from before feet existed start with healthy feet.
        public float feet = Vitals.Max;
        public float footStrain;
        public float infection, infectionRisk, antibioticHours;
        /// <summary>Hours an open cut keeps bleeding until bandaged.</summary>
        public float bleedingHours;
    }

    /// <summary>
    /// Food, water, warmth and energy, each 0–100. They change with game time (so they keep pace when
    /// time is sped up), drain faster with exertion, and slow the player down when low.
    /// Health falls while any of them is critical and recovers slowly when you're looked after.
    /// Running out of energy makes you collapse; running out of health means you need rescuing.
    /// </summary>
    public class Vitals : MonoBehaviour
    {
        public const float Max = 100f;

        [SerializeField] TimeOfDay timeOfDay;
        [SerializeField] AmbientTemperature temperature;
        [SerializeField] FirstPersonController player;
        [SerializeField] Backpack backpack;
        [SerializeField] WeatherSystem weather;

        [Header("Starting Values")]
        [SerializeField, Range(0f, Max)] float satiety = 80f;
        [SerializeField, Range(0f, Max)] float hydration = 80f;
        [SerializeField, Range(0f, Max)] float warmth = Max;
        [SerializeField, Range(0f, Max)] float energy = 90f;

        [Header("Drain per Game Hour (at rest)")]
        [SerializeField] float satietyDrain = 2.5f;
        [SerializeField] float hydrationDrain = 3.5f;
        [SerializeField] float energyDrain = 3.5f;
        [Tooltip("Energy restored per hour of sleep.")]
        [SerializeField] float sleepRecovery = 13f;

        [Header("Exertion")]
        [SerializeField] float walkingDrainMultiplier = 1.8f;
        [SerializeField] float sprintingDrainMultiplier = 3.5f;
        [Tooltip("Speed (m/s) above which you count as walking rather than resting.")]
        [SerializeField] float walkingSpeedThreshold = 0.5f;

        [Header("Warmth")]
        [Tooltip("Air temperature (°C) that feels neutral at rest with no clothing.")]
        [SerializeField] float neutralTemperature = 20f;
        [Tooltip("°C of body heat generated by walking / sprinting.")]
        [SerializeField] float walkingHeat = 5f;
        [SerializeField] float sprintingHeat = 10f;
        [Tooltip("Warmth lost per hour for each °C below comfort.")]
        [SerializeField] float coolingRate = 1.5f;
        [Tooltip("Warmth regained per hour for each °C above comfort.")]
        [SerializeField] float warmingRate = 3f;

        [Header("Rain & Wind")]
        [Tooltip("Wetness gained per hour in a full downpour without a rain shell.")]
        [SerializeField] float soakingRate = 35f;
        [Tooltip("Fraction of rain that still gets through a rain shell.")]
        [SerializeField, Range(0f, 1f)] float shellLeakage = 0.12f;
        [Tooltip("Wetness lost per hour when out of the rain, before any fire.")]
        [SerializeField] float dryingRate = 12f;
        [Tooltip("Extra drying per hour for each °C of warmth from a nearby fire.")]
        [SerializeField] float fireDryingPerDegree = 2.5f;
        [Tooltip("Fraction of clothing warmth lost when soaked through.")]
        [SerializeField, Range(0f, 1f)] float soakedInsulationLoss = 0.6f;
        [Tooltip("°C of chill from being soaked through, on top of the lost insulation.")]
        [SerializeField] float soakedChill = 3f;
        [Tooltip("°C of wind chill per km/h of wind.")]
        [SerializeField] float windChillPerKmh = 0.12f;

        [Header("Effects")]
        [SerializeField] float tiredThreshold = 30f;
        [SerializeField] float criticalThreshold = 12f;

        [Header("Feet")]
        [Tooltip("Foot strain gained per hour of walking in ordinary boots with a light pack. 100 is as sore as it gets.")]
        [SerializeField] float strainPerHour = 18f;
        [Tooltip("Strain eased per hour standing still, sitting, sitting with boots off, or asleep.")]
        [SerializeField] float idleStrainRecovery = 10f;
        [SerializeField] float seatedStrainRecovery = 35f;
        [Tooltip("Sitting in a camp chair, with your legs off the ground: feet recover this much faster than sitting on the ground.")]
        [SerializeField] float chairRecoveryFactor = 1.6f;

        [Header("Cuts")]
        [Tooltip("Health lost per hour while a cut is bleeding.")]
        [SerializeField] float bleedingDamage = 6f;
        [SerializeField] float bootsOffStrainRecovery = 90f;
        [SerializeField] float sleepingStrainRecovery = 60f;
        [Tooltip("Keep walking with strain above this and blisters start.")]
        [SerializeField] float blistersAbove = 60f;
        [Tooltip("Foot health lost per hour of walking at full strain.")]
        [SerializeField] float blisterRate = 14f;
        [Tooltip("Foot health healed per hour sitting with boots off, and per hour asleep.")]
        [SerializeField] float restingHeal = 4f;
        [Tooltip("Infection drawn out per hour holding bare feet in a campfire's smoke.")]
        [SerializeField] float smokeCure = 35f;
        [SerializeField] float sleepingHeal = 6f;

        [Header("Foot Infection")]
        [Tooltip("Hours of wet or blistered feet before an infection sets in (both at once counts double).")]
        [SerializeField] float hoursToInfection = 7f;
        [Tooltip("How fast an infection worsens, per hour.")]
        [SerializeField] float infectionGrowth = 4f;
        [Tooltip("Above this, the infection starts costing health.")]
        [SerializeField] float infectionHarmsAbove = 50f;
        [SerializeField] float infectionDamage = 3f;
        [Tooltip("How long a course of antibiotics takes to clear an infection, in hours.")]
        [SerializeField] float antibioticCourseHours = 4f;

        [Header("Health")]
        [SerializeField, Range(0f, Max)] float health = Max;
        [Tooltip("Health lost per hour with no food at all. Scales up from zero as food drops below critical.")]
        [SerializeField] float starvationDamage = 4f;
        [SerializeField] float dehydrationDamage = 8f;
        [SerializeField] float hypothermiaDamage = 20f;
        [SerializeField] float sicknessDamage = 1.5f;
        [Tooltip("Health regained per hour while food, water and warmth are above the tired threshold and you're not sick.")]
        [SerializeField] float healthRecovery = 1.5f;
        [SerializeField] float sleepingHealthRecovery = 4f;
        [Tooltip("Energy needed before you can collapse again, so one collapse doesn't chain into the next.")]
        [SerializeField] float collapseRearmEnergy = 15f;

        float sickHours;
        float wetness;
        bool collapseArmed = true;
        bool incapacitated;
        bool warnedCold, warnedHungry, warnedThirsty, warnedTired, warnedWet, warnedHurt, warnedAching, warnedBlisters, warnedRaw;
        float feet = Max, footStrain;
        float infection, infectionRisk, antibioticHours;
        bool warnedInfection;

        /// <summary>Raised when energy runs out while awake. The player passes out where they stand.</summary>
        public event System.Action Collapsed;
        /// <summary>Raised once when health reaches zero. Someone has to come and get you.</summary>
        public event System.Action Incapacitated;

        /// <summary>How wet the player's clothes are, 0 dry to 100 soaked.</summary>
        public float Wetness => wetness;
        /// <summary>Current wind chill in °C (0 when sheltered).</summary>
        public float WindChill { get; private set; }

        public float Satiety => satiety;
        public float Hydration => hydration;
        public float Warmth => warmth;
        public float Energy => energy;
        public float Health => health;
        /// <summary>Foot health, 100 healthy. Blisters bring it down.</summary>
        public float Feet => feet;
        /// <summary>How tired the feet are from walking, 0 fresh to 100. Resting eases it.</summary>
        public float FootStrain => footStrain;
        public bool HasBlisters => feet < 70f;
        /// <summary>Foot infection, 0 none to 100 severe.</summary>
        public float Infection => infection;
        public bool IsInfected => infection > 0f;
        public bool OnAntibiotics => antibioticHours > 0f;
        /// <summary>Wet or blistered feet: an infection is brewing.</summary>
        public bool FeetAtRisk => FeetWet || HasBlisters;
        /// <summary>Wet feet: soaked clothes in boots that let water in. Bare feet dry off.</summary>
        public bool FeetWet => wetness > 40f && !backpack.BootsWaterproof && !BootsOff;
        /// <summary>How close an infection is, 0 (no risk) to 1 (setting in).</summary>
        public float InfectionRisk => Mathf.Clamp01(infectionRisk / hoursToInfection);

        /// <summary>Sitting down to rest. Set by the rest mode each frame.</summary>
        public bool Seated { get; set; }
        /// <summary>Sitting in a camp chair rather than on the ground: you rest faster.</summary>
        public bool InChair { get; set; }
        /// <summary>An open cut that keeps bleeding until bandaged.</summary>
        public bool IsBleeding => bleedingHours > 0f;
        float bleedingHours;

        /// <summary>A gash from the machete: it bleeds (slowly costing health) until bandaged, or for several hours.</summary>
        public void Cut(float hours = 6f)
        {
            bool fresh = !IsBleeding;
            bleedingHours = Mathf.Max(bleedingHours, hours);
            if (fresh)
            {
                Notifications.Post("The machete glances off a branch and opens a cut on your hand. Bandage it (put bandages on your hotbar).", 6f);
                Trip.TripLog.Note("Cut my hand with the machete.");
            }
        }

        /// <summary>Stops a cut bleeding. Returns false if there's nothing to bandage.</summary>
        public bool Bandage()
        {
            if (!IsBleeding)
                return false;
            bleedingHours = 0f;
            return true;
        }

        /// <summary>Sitting with boots and socks off: feet recover fast, dry out and air.</summary>
        public bool BootsOff { get; set; }
        /// <summary>Bare feet held in a campfire's smoke: draws out infection and dries them.</summary>
        public bool SmokingFeet { get; set; }

        /// <summary>Starts a course of antibiotics, which clears an infection over a few hours.</summary>
        public void TakeAntibiotics()
        {
            antibioticHours = antibioticCourseHours;
            infectionRisk = 0f;
        }

        public bool IsSick => sickHours > 0f;
        public bool IsStarving => satiety < criticalThreshold;
        public bool IsDehydrated => hydration < criticalThreshold;
        public bool IsHypothermic => warmth < criticalThreshold;
        public bool IsExhausted => energy < criticalThreshold;
        /// <summary>Health gained per game hour right now; negative while hurting.</summary>
        public float HealthRate { get; private set; }
        public float CriticalThreshold => criticalThreshold;
        public float TiredThreshold => tiredThreshold;

        /// <summary>Set while sleeping; sleeping uses the sleeping bag instead of clothing.</summary>
        public bool IsSleeping { get; set; }
        /// <summary>Set while sleeping inside a tent.</summary>
        public bool IsSheltered { get; set; }
        /// <summary>Set while asleep in the sleeping bag. Passing out on the ground leaves you in your clothes.</summary>
        public bool InSleepingBag { get; set; }
        /// <summary>Set while sitting in the truck's cab: out of the rain and wind, with the heater on.</summary>
        public bool InVehicle { get; set; }

        /// <summary>Degrees the truck's heater adds to the air in the cab.</summary>
        const float CabHeater = 10f;
        /// <summary>Degrees of comfort a soaked sleeping bag loses.</summary>
        const float WetBagLoss = 12f;

        /// <summary>Air temperature the player feels, including fires and shelter (°C).</summary>
        public float FeltTemperature { get; private set; }
        /// <summary>The temperature (°C) below which the player starts losing warmth.</summary>
        public float ComfortTemperature { get; private set; }

        public void Eat(float amount) => satiety = Mathf.Min(Max, satiety + amount);
        public void Drink(float amount) => hydration = Mathf.Min(Max, hydration + amount);
        public void MakeSick(float hours) => sickHours = Mathf.Max(sickHours, hours);
        /// <summary>A sudden injury (a lightning strike nearby): takes <paramref name="amount"/> health straight away.</summary>
        public void Hurt(float amount) => health = Mathf.Max(0f, health - amount);

        /// <summary>Hard physical work, like chopping: costs energy and makes you thirsty.</summary>
        public void Exert(float energyCost)
        {
            energy = Mathf.Max(0f, energy - energyCost);
            hydration = Mathf.Max(0f, hydration - energyCost * 0.4f);
        }

        /// <summary>Sets every vital at once, e.g. after a rescue. Also dries you off and cures sickness.</summary>
        public void Recover(float newHealth, float newSatiety, float newHydration, float newWarmth, float newEnergy)
        {
            health = newHealth;
            satiety = newSatiety;
            hydration = newHydration;
            warmth = newWarmth;
            energy = newEnergy;
            wetness = 0f;
            sickHours = 0f;
            incapacitated = false;
            collapseArmed = true;
        }

        public VitalsState CaptureState() => new()
        {
            satiety = satiety,
            hydration = hydration,
            warmth = warmth,
            energy = energy,
            sickHours = sickHours,
            wetness = wetness,
            health = health,
            feet = feet,
            footStrain = footStrain,
            infection = infection,
            infectionRisk = infectionRisk,
            antibioticHours = antibioticHours,
            bleedingHours = bleedingHours,
        };

        public void RestoreState(VitalsState state)
        {
            satiety = state.satiety;
            hydration = state.hydration;
            warmth = state.warmth;
            energy = state.energy;
            sickHours = state.sickHours;
            wetness = state.wetness;
            // Saves from before health existed have no value for it.
            health = state.health > 0f ? state.health : Max;
            feet = state.feet > 0f ? state.feet : Max;
            footStrain = state.footStrain;
            infection = state.infection;
            infectionRisk = state.infectionRisk;
            antibioticHours = state.antibioticHours;
            bleedingHours = state.bleedingHours;
            incapacitated = false;
            collapseArmed = energy > collapseRearmEnergy;
        }

        void Update()
        {
            float hours = Time.deltaTime * timeOfDay.HoursPerSecond;
            if (hours <= 0f)
                return;

            bool moving = !IsSleeping && player.HorizontalSpeed > walkingSpeedThreshold;
            bool sprinting = moving && player.IsSprinting;
            float exertion = sprinting ? sprintingDrainMultiplier : moving ? walkingDrainMultiplier : 1f;
            // A heavy pack makes every step cost more.
            if (moving)
                exertion *= backpack.LoadExertionMultiplier;
            float sickness = IsSick ? 2f : 1f;

            satiety = Mathf.Max(0f, satiety - satietyDrain * exertion * Mathf.Sqrt(sickness) * hours);
            hydration = Mathf.Max(0f, hydration - hydrationDrain * exertion * sickness * hours);
            sickHours = Mathf.Max(0f, sickHours - hours);

            UpdateWarmth(hours, sprinting ? sprintingHeat : moving ? walkingHeat : 0f);
            UpdateFeet(hours, moving, sprinting);

            // A mat between you and the ground makes for better sleep.
            if (IsSleeping)
                energy = Mathf.Min(Max, energy + sleepRecovery * (InSleepingBag ? backpack.MatRecovery : 1f) * hours);
            else
            {
                // Being frozen or starving wears you out much faster.
                float strain = warmth <= 0f || satiety <= 0f || hydration <= 0f ? 3f : 1f;
                // Limping on raw feet is tiring.
                if (moving && feet < 40f)
                    strain *= 1.25f;
                // Fighting an infection wears you out.
                if (infection > 30f)
                    strain *= 1.3f;
                energy = Mathf.Max(0f, energy - energyDrain * exertion * strain * hours);
            }

            UpdateHealth(hours);
            CheckCollapse();

            ApplyEffects();
            WarnOnce(ref warnedCold, warmth, 40f, "You're getting cold. Put on a layer or find warmth.");
            WarnOnce(ref warnedHungry, satiety, 25f, "You're hungry.");
            WarnOnce(ref warnedThirsty, hydration, 25f, "You're thirsty.");
            WarnOnce(ref warnedTired, energy, 20f, "You're exhausted. Sleep soon or you'll collapse.");
            WarnOnce(ref warnedHurt, health, 40f, HurtWarning());
            WarnOnce(ref warnedAching, Max - footStrain, Max - blistersAbove,
                "Your feet are aching. Sit down (Z) and take your boots off (E) to rest them, or you'll get blisters.");
            WarnOnce(ref warnedRaw, feet, 40f, "Your feet are raw. You're limping badly. Sit with your boots off (Z, then E) and sleep to let them heal.");
            if (!warnedBlisters && feet < 70f)
            {
                warnedBlisters = true;
                Notifications.Post("Blisters. Every step hurts now. Sit with your boots off (Z, then E), and sleep to let them heal.");
                Trip.TripLog.Note("Blisters on both feet. Pushed too far without a rest.");
            }
            else if (warnedBlisters && feet > 85f)
                warnedBlisters = false;
        }

        /// <summary>
        /// Walking tires the feet, faster with a heavy pack, at a sprint, in wet or poor boots. Keep going on
        /// aching feet and blisters form; rest eases the ache and sleep heals the blisters.
        /// </summary>
        void UpdateFeet(float hours, bool moving, bool sprinting)
        {
            if (moving)
            {
                bool wetFeet = wetness > 40f && !backpack.BootsWaterproof;
                float rate = strainPerHour * backpack.BootsStrain * (sprinting ? 1.8f : 1f)
                             * (1f + 0.6f * player.LoadFactor) * (wetFeet ? 1.4f : 1f);
                footStrain = Mathf.Min(Max, footStrain + rate * hours);
                if (footStrain > blistersAbove)
                    feet -= blisterRate * (footStrain - blistersAbove) / (Max - blistersAbove) * hours;
            }
            else
            {
                float recovery = IsSleeping ? sleepingStrainRecovery : BootsOff ? bootsOffStrainRecovery
                    : Seated ? seatedStrainRecovery : idleStrainRecovery;
                if (InChair && !IsSleeping)
                    recovery *= chairRecoveryFactor;
                footStrain = Mathf.Max(0f, footStrain - recovery * hours);
                // An infection keeps blisters from healing.
                if (footStrain < blistersAbove && (IsSleeping || BootsOff) && !IsInfected)
                    feet += (IsSleeping ? sleepingHeal : restingHeal) * hours;
            }
            feet = Mathf.Clamp(feet, 0f, Max);
            UpdateInfection(hours);
        }

        /// <summary>Feet kept wet or blistered too long get infected; antibiotics or smoking them over a fire cures it.</summary>
        void UpdateInfection(float hours)
        {
            float exposure = (FeetWet ? 1f : 0f) + (HasBlisters ? 1f : 0f);
            if (exposure > 0f && !OnAntibiotics && !BootsOff)
                infectionRisk += exposure * hours;
            else
                // Airing the feet clears the risk much faster.
                infectionRisk = Mathf.Max(0f, infectionRisk - (BootsOff ? 3f : 0.5f) * hours);

            if (SmokingFeet)
            {
                bool wasInfected = IsInfected;
                infection = Mathf.Max(0f, infection - smokeCure * hours);
                infectionRisk = 0f;
                wetness = Mathf.Max(0f, wetness - 60f * hours);
                if (wasInfected && !IsInfected)
                {
                    Notifications.Post("The swelling's gone down. The smoke has drawn out the infection.");
                    Trip.TripLog.Note("Held my bare feet in the fire's smoke until the infection cleared.");
                }
            }

            if (!IsInfected && infectionRisk >= hoursToInfection)
            {
                infection = 10f;
                Notifications.Post("Your feet are red, hot and swollen: an infection. Take antibiotics, or smoke your feet over a fire.", 8f);
                Trip.TripLog.Note("My feet are infected. Should have kept them dry.");
                warnedInfection = true;
            }

            if (OnAntibiotics)
            {
                antibioticHours = Mathf.Max(0f, antibioticHours - hours);
                infection = Mathf.Max(0f, infection - 100f / antibioticCourseHours * hours);
                if (IsInfected && infection <= 0f)
                    Trip.TripLog.Note("The antibiotics did their job. The infection's gone.");
            }
            else if (IsInfected)
                infection = Mathf.Min(Max, infection + infectionGrowth * (1f + 0.5f * exposure) * hours);

            if (infection <= 0f)
                warnedInfection = false;
        }

        void UpdateHealth(float hours)
        {
            if (incapacitated)
                return;

            // Each vital starts hurting below critical, and hurts more the closer it gets to empty.
            float damage = (infection > infectionHarmsAbove ? infectionDamage * Mathf.InverseLerp(infectionHarmsAbove, Max, infection) * 2f : 0f)
                           + starvationDamage * Deficit(satiety)
                           + dehydrationDamage * Deficit(hydration)
                           + hypothermiaDamage * Deficit(warmth)
                           + (IsSick ? sicknessDamage : 0f)
                           + (IsBleeding ? bleedingDamage : 0f);
            bleedingHours = Mathf.Max(0f, bleedingHours - hours);

            // Energy doesn't count here: sleep is how it comes back, and sleep should heal.
            float lowest = Mathf.Min(satiety, Mathf.Min(hydration, warmth));
            bool lookedAfter = damage <= 0f && lowest > tiredThreshold;
            float recovery = lookedAfter ? (IsSleeping ? sleepingHealthRecovery : healthRecovery) : 0f;

            HealthRate = recovery - damage;
            health = Mathf.Clamp(health + HealthRate * hours, 0f, Max);
            if (health <= 0f)
            {
                incapacitated = true;
                Incapacitated?.Invoke();
            }
        }

        float Deficit(float value) => value >= criticalThreshold ? 0f : 1f - value / criticalThreshold;

        void CheckCollapse()
        {
            if (IsSleeping || incapacitated)
                return;
            if (!collapseArmed && energy > collapseRearmEnergy)
                collapseArmed = true;
            if (collapseArmed && energy <= 0f)
            {
                collapseArmed = false;
                Collapsed?.Invoke();
            }
        }

        string HurtWarning()
        {
            if (IsHypothermic)
                return "You're hypothermic and getting weaker. Get warm now: a fire, dry layers or your sleeping bag.";
            if (IsDehydrated)
                return "You're badly dehydrated and getting weaker. Drink something.";
            if (IsStarving)
                return "You're starving and getting weaker. Eat something.";
            return "You're in bad shape. Rest, eat and stay warm.";
        }

        void UpdateWetness(float hours, float fireWarmth)
        {
            bool covered = (IsSleeping && IsSheltered) || InVehicle;
            float rain = weather != null && !covered ? weather.RainIntensity : 0f;
            float soaking = rain * soakingRate * (backpack.WearingWaterproof ? shellLeakage : 1f);
            float drying = (rain > 0.05f ? 0f : dryingRate) + fireWarmth * fireDryingPerDegree;
            wetness = Mathf.Clamp(wetness + (soaking - drying) * hours, 0f, Max);
            WarnOnce(ref warnedWet, Max - wetness, Max - 50f, "You're getting soaked. Put on your rain shell or find shelter.");
            float bagWasWet = backpack.BagWetness;
            backpack.WeatherTheBag(weather != null && !InVehicle ? weather.RainIntensity : 0f, hours, fireWarmth);
            if (bagWasWet < 0.3f && backpack.BagWetness >= 0.3f)
                Notifications.Post("The rain's soaking the sleeping bag strapped to the outside of your pack. A wet bag is a cold night: pack it inside.", 8f);
        }

        void UpdateWarmth(float hours, float bodyHeat)
        {
            float air = temperature.GetTemperature(transform.position);
            float fire = HeatSource.WarmthAt(transform.position);
            UpdateWetness(hours, fire);

            bool inTent = IsSleeping && IsSheltered;
            WindChill = weather != null && !inTent && !InVehicle ? weather.WindKmh * windChillPerKmh : 0f;
            float soaked = wetness / Max;
            FeltTemperature = air + fire + (inTent ? backpack.TentShelter : 0f) + (InVehicle ? CabHeater : 0f) - WindChill - soaked * soakedChill;

            float insulation = (backpack.ClothingInsulation + backpack.BootsWarmth + HikerTraits.InsulationBonus) * (1f - soakedInsulationLoss * soaked);
            // In the bag, a mat stops the ground drawing the heat out of you. A wet bag loses most of its warmth.
            ComfortTemperature = IsSleeping && InSleepingBag && backpack.HasSleepingBag
                ? backpack.SleepingBagComfort + backpack.BagWetness * WetBagLoss - backpack.MatWarmth
                : neutralTemperature - insulation - bodyHeat - (IsSleeping ? backpack.MatWarmth : 0f);

            float difference = FeltTemperature - ComfortTemperature;
            float rate = difference < 0f ? coolingRate : warmingRate;
            warmth = Mathf.Clamp(warmth + difference * rate * hours, 0f, Max);
        }

        void ApplyEffects()
        {
            float lowest = Mathf.Min(Mathf.Min(satiety, hydration), Mathf.Min(Mathf.Min(warmth, energy), health));
            float condition = lowest < criticalThreshold ? 0.6f : lowest < tiredThreshold ? 0.85f : 1f;
            // Sore feet slow you down; blisters make you limp.
            float footing = feet < 15f ? 0.5f : feet < 40f ? 0.7f : feet < 70f ? 0.88f : footStrain > 85f ? 0.92f : 1f;
            player.SpeedMultiplier = condition * footing * backpack.LoadSpeedMultiplier * HikerTraits.SpeedFactor;
            player.Limp = Mathf.InverseLerp(75f, 15f, feet);
            // From a light day pack (5 kg) up to all you can carry.
            player.LoadFactor = Mathf.InverseLerp(5f, backpack.MaxLoad, backpack.CarriedWeight);
            player.CanSprint = energy > criticalThreshold && hydration > criticalThreshold && health > tiredThreshold
                               && feet >= 40f && !backpack.IsOverloaded;
        }

        /// <summary>Posts a message when a value drops below a threshold, then rearms once it recovers.</summary>
        static void WarnOnce(ref bool warned, float value, float threshold, string message)
        {
            if (!warned && value < threshold)
            {
                warned = true;
                Notifications.Post(message);
            }
            else if (warned && value > threshold + 10f)
                warned = false;
        }
    }
}
