using Backpacking.Player;
using Backpacking.UI;
using Backpacking.World;
using UnityEngine;

namespace Backpacking.Survival
{
    [System.Serializable]
    public class VitalsState
    {
        public float satiety, hydration, warmth, energy, sickHours, wetness;
        public float health = Vitals.Max;
    }

    /// <summary>
    /// Food, water, warmth and energy, each 0–100. They change with game time (so they keep pace when
    /// time is sped up), drain faster with exertion, and slow the player down when low.
    /// Health falls while any of them is critical and recovers slowly when you're looked after.
    /// Running out of energy makes you collapse; running out of health means you need rescuing.
    /// </summary>
    public class Vitals : MonoBehaviour
    {
        public const float Max = 100f;

        [SerializeField] TimeOfDay timeOfDay;
        [SerializeField] AmbientTemperature temperature;
        [SerializeField] FirstPersonController player;
        [SerializeField] Backpack backpack;
        [SerializeField] WeatherSystem weather;

        [Header("Starting Values")]
        [SerializeField, Range(0f, Max)] float satiety = 80f;
        [SerializeField, Range(0f, Max)] float hydration = 80f;
        [SerializeField, Range(0f, Max)] float warmth = Max;
        [SerializeField, Range(0f, Max)] float energy = 90f;

        [Header("Drain per Game Hour (at rest)")]
        [SerializeField] float satietyDrain = 2.5f;
        [SerializeField] float hydrationDrain = 3.5f;
        [SerializeField] float energyDrain = 3.5f;
        [Tooltip("Energy restored per hour of sleep.")]
        [SerializeField] float sleepRecovery = 13f;

        [Header("Exertion")]
        [SerializeField] float walkingDrainMultiplier = 1.8f;
        [SerializeField] float sprintingDrainMultiplier = 3.5f;
        [Tooltip("Speed (m/s) above which you count as walking rather than resting.")]
        [SerializeField] float walkingSpeedThreshold = 0.5f;

        [Header("Warmth")]
        [Tooltip("Air temperature (°C) that feels neutral at rest with no clothing.")]
        [SerializeField] float neutralTemperature = 20f;
        [Tooltip("°C of body heat generated by walking / sprinting.")]
        [SerializeField] float walkingHeat = 5f;
        [SerializeField] float sprintingHeat = 10f;
        [Tooltip("Warmth lost per hour for each °C below comfort.")]
        [SerializeField] float coolingRate = 1.5f;
        [Tooltip("Warmth regained per hour for each °C above comfort.")]
        [SerializeField] float warmingRate = 3f;

        [Header("Rain & Wind")]
        [Tooltip("Wetness gained per hour in a full downpour without a rain shell.")]
        [SerializeField] float soakingRate = 35f;
        [Tooltip("Fraction of rain that still gets through a rain shell.")]
        [SerializeField, Range(0f, 1f)] float shellLeakage = 0.12f;
        [Tooltip("Wetness lost per hour when out of the rain, before any fire.")]
        [SerializeField] float dryingRate = 12f;
        [Tooltip("Extra drying per hour for each °C of warmth from a nearby fire.")]
        [SerializeField] float fireDryingPerDegree = 2.5f;
        [Tooltip("Fraction of clothing warmth lost when soaked through.")]
        [SerializeField, Range(0f, 1f)] float soakedInsulationLoss = 0.6f;
        [Tooltip("°C of chill from being soaked through, on top of the lost insulation.")]
        [SerializeField] float soakedChill = 3f;
        [Tooltip("°C of wind chill per km/h of wind.")]
        [SerializeField] float windChillPerKmh = 0.12f;

        [Header("Effects")]
        [SerializeField] float tiredThreshold = 30f;
        [SerializeField] float criticalThreshold = 12f;

        [Header("Health")]
        [SerializeField, Range(0f, Max)] float health = Max;
        [Tooltip("Health lost per hour with no food at all. Scales up from zero as food drops below critical.")]
        [SerializeField] float starvationDamage = 4f;
        [SerializeField] float dehydrationDamage = 8f;
        [SerializeField] float hypothermiaDamage = 20f;
        [SerializeField] float sicknessDamage = 1.5f;
        [Tooltip("Health regained per hour while food, water and warmth are above the tired threshold and you're not sick.")]
        [SerializeField] float healthRecovery = 1.5f;
        [SerializeField] float sleepingHealthRecovery = 4f;
        [Tooltip("Energy needed before you can collapse again, so one collapse doesn't chain into the next.")]
        [SerializeField] float collapseRearmEnergy = 15f;

        float sickHours;
        float wetness;
        bool collapseArmed = true;
        bool incapacitated;
        bool warnedCold, warnedHungry, warnedThirsty, warnedTired, warnedWet, warnedHurt;

        /// <summary>Raised when energy runs out while awake. The player passes out where they stand.</summary>
        public event System.Action Collapsed;
        /// <summary>Raised once when health reaches zero. Someone has to come and get you.</summary>
        public event System.Action Incapacitated;

        /// <summary>How wet the player's clothes are, 0 dry to 100 soaked.</summary>
        public float Wetness => wetness;
        /// <summary>Current wind chill in °C (0 when sheltered).</summary>
        public float WindChill { get; private set; }

        public float Satiety => satiety;
        public float Hydration => hydration;
        public float Warmth => warmth;
        public float Energy => energy;
        public float Health => health;
        public bool IsSick => sickHours > 0f;
        public bool IsStarving => satiety < criticalThreshold;
        public bool IsDehydrated => hydration < criticalThreshold;
        public bool IsHypothermic => warmth < criticalThreshold;
        public bool IsExhausted => energy < criticalThreshold;
        /// <summary>Health gained per game hour right now; negative while hurting.</summary>
        public float HealthRate { get; private set; }
        public float CriticalThreshold => criticalThreshold;
        public float TiredThreshold => tiredThreshold;

        /// <summary>Set while sleeping; sleeping uses the sleeping bag instead of clothing.</summary>
        public bool IsSleeping { get; set; }
        /// <summary>Set while sleeping inside a tent.</summary>
        public bool IsSheltered { get; set; }
        /// <summary>Set while asleep in the sleeping bag. Passing out on the ground leaves you in your clothes.</summary>
        public bool InSleepingBag { get; set; }

        /// <summary>Air temperature the player feels, including fires and shelter (°C).</summary>
        public float FeltTemperature { get; private set; }
        /// <summary>The temperature (°C) below which the player starts losing warmth.</summary>
        public float ComfortTemperature { get; private set; }

        public void Eat(float amount) => satiety = Mathf.Min(Max, satiety + amount);
        public void Drink(float amount) => hydration = Mathf.Min(Max, hydration + amount);
        public void MakeSick(float hours) => sickHours = Mathf.Max(sickHours, hours);

        /// <summary>Hard physical work, like chopping: costs energy and makes you thirsty.</summary>
        public void Exert(float energyCost)
        {
            energy = Mathf.Max(0f, energy - energyCost);
            hydration = Mathf.Max(0f, hydration - energyCost * 0.4f);
        }

        /// <summary>Sets every vital at once, e.g. after a rescue. Also dries you off and cures sickness.</summary>
        public void Recover(float newHealth, float newSatiety, float newHydration, float newWarmth, float newEnergy)
        {
            health = newHealth;
            satiety = newSatiety;
            hydration = newHydration;
            warmth = newWarmth;
            energy = newEnergy;
            wetness = 0f;
            sickHours = 0f;
            incapacitated = false;
            collapseArmed = true;
        }

        public VitalsState CaptureState() => new()
        {
            satiety = satiety,
            hydration = hydration,
            warmth = warmth,
            energy = energy,
            sickHours = sickHours,
            wetness = wetness,
            health = health,
        };

        public void RestoreState(VitalsState state)
        {
            satiety = state.satiety;
            hydration = state.hydration;
            warmth = state.warmth;
            energy = state.energy;
            sickHours = state.sickHours;
            wetness = state.wetness;
            // Saves from before health existed have no value for it.
            health = state.health > 0f ? state.health : Max;
            incapacitated = false;
            collapseArmed = energy > collapseRearmEnergy;
        }

        void Update()
        {
            float hours = Time.deltaTime * timeOfDay.HoursPerSecond;
            if (hours <= 0f)
                return;

            bool moving = !IsSleeping && player.HorizontalSpeed > walkingSpeedThreshold;
            bool sprinting = moving && player.IsSprinting;
            float exertion = sprinting ? sprintingDrainMultiplier : moving ? walkingDrainMultiplier : 1f;
            // A heavy pack makes every step cost more.
            if (moving)
                exertion *= backpack.LoadExertionMultiplier;
            float sickness = IsSick ? 2f : 1f;

            satiety = Mathf.Max(0f, satiety - satietyDrain * exertion * Mathf.Sqrt(sickness) * hours);
            hydration = Mathf.Max(0f, hydration - hydrationDrain * exertion * sickness * hours);
            sickHours = Mathf.Max(0f, sickHours - hours);

            UpdateWarmth(hours, sprinting ? sprintingHeat : moving ? walkingHeat : 0f);

            if (IsSleeping)
                energy = Mathf.Min(Max, energy + sleepRecovery * hours);
            else
            {
                // Being frozen or starving wears you out much faster.
                float strain = warmth <= 0f || satiety <= 0f || hydration <= 0f ? 3f : 1f;
                energy = Mathf.Max(0f, energy - energyDrain * exertion * strain * hours);
            }

            UpdateHealth(hours);
            CheckCollapse();

            ApplyEffects();
            WarnOnce(ref warnedCold, warmth, 40f, "You're getting cold. Put on a layer or find warmth.");
            WarnOnce(ref warnedHungry, satiety, 25f, "You're hungry.");
            WarnOnce(ref warnedThirsty, hydration, 25f, "You're thirsty.");
            WarnOnce(ref warnedTired, energy, 20f, "You're exhausted. Sleep soon or you'll collapse.");
            WarnOnce(ref warnedHurt, health, 40f, HurtWarning());
        }

        void UpdateHealth(float hours)
        {
            if (incapacitated)
                return;

            // Each vital starts hurting below critical, and hurts more the closer it gets to empty.
            float damage = starvationDamage * Deficit(satiety)
                           + dehydrationDamage * Deficit(hydration)
                           + hypothermiaDamage * Deficit(warmth)
                           + (IsSick ? sicknessDamage : 0f);

            // Energy doesn't count here: sleep is how it comes back, and sleep should heal.
            float lowest = Mathf.Min(satiety, Mathf.Min(hydration, warmth));
            bool lookedAfter = damage <= 0f && lowest > tiredThreshold;
            float recovery = lookedAfter ? (IsSleeping ? sleepingHealthRecovery : healthRecovery) : 0f;

            HealthRate = recovery - damage;
            health = Mathf.Clamp(health + HealthRate * hours, 0f, Max);
            if (health <= 0f)
            {
                incapacitated = true;
                Incapacitated?.Invoke();
            }
        }

        float Deficit(float value) => value >= criticalThreshold ? 0f : 1f - value / criticalThreshold;

        void CheckCollapse()
        {
            if (IsSleeping || incapacitated)
                return;
            if (!collapseArmed && energy > collapseRearmEnergy)
                collapseArmed = true;
            if (collapseArmed && energy <= 0f)
            {
                collapseArmed = false;
                Collapsed?.Invoke();
            }
        }

        string HurtWarning()
        {
            if (IsHypothermic)
                return "You're hypothermic and getting weaker. Get warm now: a fire, dry layers or your sleeping bag.";
            if (IsDehydrated)
                return "You're badly dehydrated and getting weaker. Drink something.";
            if (IsStarving)
                return "You're starving and getting weaker. Eat something.";
            return "You're in bad shape. Rest, eat and stay warm.";
        }

        void UpdateWetness(float hours, float fireWarmth)
        {
            bool inTent = IsSleeping && IsSheltered;
            float rain = weather != null && !inTent ? weather.RainIntensity : 0f;
            float soaking = rain * soakingRate * (backpack.WearingWaterproof ? shellLeakage : 1f);
            float drying = (rain > 0.05f ? 0f : dryingRate) + fireWarmth * fireDryingPerDegree;
            wetness = Mathf.Clamp(wetness + (soaking - drying) * hours, 0f, Max);
            WarnOnce(ref warnedWet, Max - wetness, Max - 50f, "You're getting soaked. Put on your rain shell or find shelter.");
        }

        void UpdateWarmth(float hours, float bodyHeat)
        {
            float air = temperature.GetTemperature(transform.position);
            float fire = HeatSource.WarmthAt(transform.position);
            UpdateWetness(hours, fire);

            bool inTent = IsSleeping && IsSheltered;
            WindChill = weather != null && !inTent ? weather.WindKmh * windChillPerKmh : 0f;
            float soaked = wetness / Max;
            FeltTemperature = air + fire + (inTent ? backpack.TentShelter : 0f) - WindChill - soaked * soakedChill;

            float insulation = backpack.ClothingInsulation * (1f - soakedInsulationLoss * soaked);
            ComfortTemperature = IsSleeping && InSleepingBag
                ? backpack.SleepingBagComfort
                : neutralTemperature - insulation - bodyHeat;

            float difference = FeltTemperature - ComfortTemperature;
            float rate = difference < 0f ? coolingRate : warmingRate;
            warmth = Mathf.Clamp(warmth + difference * rate * hours, 0f, Max);
        }

        void ApplyEffects()
        {
            float lowest = Mathf.Min(Mathf.Min(satiety, hydration), Mathf.Min(Mathf.Min(warmth, energy), health));
            float condition = lowest < criticalThreshold ? 0.6f : lowest < tiredThreshold ? 0.85f : 1f;
            player.SpeedMultiplier = condition * backpack.LoadSpeedMultiplier;
            player.CanSprint = energy > criticalThreshold && hydration > criticalThreshold && health > tiredThreshold
                               && !backpack.IsOverloaded;
        }

        /// <summary>Posts a message when a value drops below a threshold, then rearms once it recovers.</summary>
        static void WarnOnce(ref bool warned, float value, float threshold, string message)
        {
            if (!warned && value < threshold)
            {
                warned = true;
                Notifications.Post(message);
            }
            else if (warned && value > threshold + 10f)
                warned = false;
        }
    }
}
